emitters = {
        -- Darkscape, west of the sawmill (Small Metal)
    {
        x = 234.376, y = 0.695, z = -177.827,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- Darkscape, west of the sawmill (Small Metal)
    {
        x = 231.882, y = 1.850, z = -182.354,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- Darkscape, west of the sawmill (Small Metal)
    {
        x = -175.209, y = 2.033, z = -159.207,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- Darkscape, west of the sawmill (Small Metal)
    {
        x = 226.133, y = -0.437, z = -176.443,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- Darkscape, east of the sawmill (Small Metal)
    {
        x = 274.464, y = -0.523, z = -187.853,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- Darkscape, south-west of the gas station (Small Metal)
    {
        x = 418.185, y = -1.619, z = -370.875,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- Darkscape, at the gas station (Small Metal)
    {
        x = 429.850, y = -1.811, z = -360.008,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- Darkscape, east of the bridge (Hangar Complex)
    {
        x = 404.142, y = 18.374, z = 283.137,
        max_hearing_dist = 180.0,
        sound_list = {
            {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            {name="hangar_metal_details", chance = 0.9, interval = 35, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
        }
    },
    -- Darkscape, north-west of the bridge (Hangar Complex)
    {
        x = 396.500, y = 19.422, z = 288.921,
        max_hearing_dist = 180.0,
        sound_list = {
            {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            {name="hangar_metal_details", chance = 0.9, interval = 35, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
        }
    },
    -- Darkscape, west of the bridge (Hangar Complex)
    {
        x = 368.735, y = 20.468, z = 287.544,
        max_hearing_dist = 180.0,
        sound_list = {
            {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            {name="hangar_metal_details", chance = 0.9, interval = 35, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
        }
    },

-- Darkscape, near the sawmill
    {
        x = 250.444, y = 3.885, z = -186.322,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="interior_detail_wood", chance = 1.0, interval = 8, sound_list_size = 25, last_time = 0, base_volume = 0.9, min_dist = 1.0, max_dist = 1.5},
        }
    },
    -- Darkscape, east of the sawmill
    {
        x = 267.870, y = -0.220, z = -190.952,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="interior_detail_wood", chance = 1.0, interval = 8, sound_list_size = 25, last_time = 0, base_volume = 0.9, min_dist = 1.0, max_dist = 1.5},
        }
    },

-- Darkscape, north-west of the bridge (FROGS)
    {
        x = 241.711, y = -5.069, z = 548.196,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 6, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 8, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- Darkscape, north-west of the bridge (FROGS)
    {
        x = 235.757, y = -4.512, z = 553.669,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 6, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 8, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- Darkscape, north of the bridge (FROGS)
    {
        x = 242.632, y = -4.064, z = 579.021,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 6, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 8, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- Darkscape, north of the bridge (FROGS)
    {
        x = 239.372, y = -4.129, z = 594.873,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 6, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 8, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- Darkscape, north of the bridge (FROGS)
    {
        x = 241.304, y = -4.074, z = 610.568,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 6, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 8, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- Darkscape, north of the bridge (FROGS)
    {
        x = 235.218, y = -2.955, z = 621.711,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 6, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 8, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
}
