emitters = {
        -- 1. South-east of the Rostok checkpoint
        {
            x = 150.028, y = -6.268, z = 104.055,
            max_hearing_dist = 80.0,
            sound_list = {
                {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 1.5, min_dist = 15.0, max_dist = 25.0},
                {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 1.5, min_dist = 10.0, max_dist = 15.0},
            }
        },
        -- 2. South of the Rostok checkpoint
        {
            x = 80.564, y = -0.233, z = 132.679,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 3. South-east of the Rostok checkpoint (2)
        {
            x = 99.487, y = 3.727, z = 168.784,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="generic_concrete_large_room", chance = 0.9, interval = 20, sound_list_size = 17, last_time = 0, base_volume = 1.8, min_dist = 5.0, max_dist = 13.0},
                {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 13.0},
            }
        },
        {
            x = -33.338, y = 0.482, z = 12.948,
            max_hearing_dist = 180.0,
            sound_list = {
                {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_metal_details", chance = 0.9, interval = 35, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},

            }
        },
        {
            x = -58.908, y = 0.559, z = 11.025,
            max_hearing_dist = 190.0,
            sound_list = {
                {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_metal_details", chance = 0.9, interval = 40, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
                {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
            }
        },
        {
            x = 90.483, y = 0.393, z = 9.430,
            max_hearing_dist = 180.0,
            sound_list = {
                {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_metal_details", chance = 0.9, interval = 40, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            }
        },
        {
            x = -79.003, y = 10.287, z = 2.088,
            max_hearing_dist = 170.0,
            sound_list = {
                {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_metal_details", chance = 0.9, interval = 40, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            }
        },
        {
            x = -105.762, y = 0.344, z = 9.872,
            max_hearing_dist = 190.0,
            sound_list = {
                {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_metal_details", chance = 0.9, interval = 40, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            }
        },
-- Garbage, east of the Depot
    {
        x = -64.548, y = 14.250, z = 4.816,
        max_hearing_dist = 180.0,
        sound_list = {
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 60, sound_list_size = 16, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 10.0},
        }
    },
    -- Garbage, east of the Depot
    {
        x = -67.199, y = 18.246, z = 16.928,
        max_hearing_dist = 190.0,
        sound_list = {
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 41, sound_list_size = 16, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 38, sound_list_size = 16, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 10.0},
        }
    },
    -- Garbage, east of the Depot
    {
        x = -83.834, y = 18.936, z = 13.790,
        max_hearing_dist = 210.0,
        sound_list = {
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 10.0},
        }
    },
    -- Garbage, east of the Depot
    {
        x = -96.799, y = 19.152, z = 11.335,
        max_hearing_dist = 200.0,
        sound_list = {
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 45, sound_list_size = 16, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 10.0},
        }
    },
    -- Garbage, east of the Depot
    {
        x = -108.281, y = 19.163, z = 11.372,
        max_hearing_dist = 190.0,
        sound_list = {
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 40, sound_list_size = 16, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 35, sound_list_size = 16, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 10.0},
        }
    },
    }