-- ARCHIVO: amb_map_pripyat.script

emitters = {
    -- 1. South-west of the Volcano anomaly
    {
        x = -233.780, y = 2.169, z = -108.434,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 2. North-west of the grocery store
    {
        x = -240.636, y = 2.965, z = -146.309,
        max_hearing_dist = 160.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 3. North-west of the grocery store (2)
    {
        x = -240.604, y = 2.989, z = -158.593,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 4. West of the grocery store
    {
        x = -241.101, y = -0.428, z = -182.423,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 5. West of the grocery store (2)
    {
        x = -241.149, y = 2.991, z = -201.686,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 6. West of the grocery store (3)
    {
        x = -240.362, y = 2.980, z = -217.862,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 7. South-west of the grocery store
    {
        x = -240.663, y = 0.962, z = -251.393,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 8. South of the grocery store
    {
        x = -184.773, y = 2.184, z = -250.578,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 9. North of the grocery store
    {
        x = -208.392, y = 2.188, z = -152.586,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 10. West of the playground
    {
        x = -172.494, y = 2.231, z = -108.460,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 11. South-west of the playground
    {
        x = -151.372, y = 2.168, z = -135.482,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 12. South of the Volcano anomaly
    {
        x = -178.128, y = -0.428, z = -92.441,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 13. South of the Volcano anomaly (2)
    {
        x = -213.599, y = -0.428, z = -92.339,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 14. West of the Volcano anomaly
    {
        x = -240.900, y = -0.435, z = -61.517,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 15. West of the Volcano anomaly (2)
    {
        x = -240.938, y = 2.981, z = -16.223,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 16. North-west of the Volcano anomaly
    {
        x = -240.408, y = -0.443, z = 14.709,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 23. East of the Volcano anomaly (Metal - Primera de la lista)
    {
        x = -161.170, y = 0.707, z = -28.536,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 24. North-east of the Volcano anomaly (Urban)
    {
        x = -152.908, y = -0.500, z = 1.361,
        max_hearing_dist = 125.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 25. North-west of the Volcano anomaly (Urban)
    {
        x = -208.742, y = -0.430, z = 1.856,
        max_hearing_dist = 115.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 26. North of the Volcano anomaly (Urban)
    {
        x = -207.634, y = -0.427, z = 56.608,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 27. North of the Volcano anomaly (Urban)
    {
        x = -171.769, y = -0.427, z = 62.726,
        max_hearing_dist = 145.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 28. West of KBO Jubilee (Urban)
    {
        x = -138.764, y = 2.212, z = 80.068,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 29. North-west of KBO Jubilee (Urban)
    {
        x = -104.894, y = 2.383, z = 130.318,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 30. North of KBO Jubilee (Urban)
    {
        x = -82.111, y = -0.428, z = 153.338,
        max_hearing_dist = 135.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 31. North of KBO Jubilee (Urban)
    {
        x = -62.509, y = -0.427, z = 152.991,
        max_hearing_dist = 148.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 32. North of KBO Jubilee (Urban)
    {
        x = -37.233, y = -0.427, z = 156.911,
        max_hearing_dist = 122.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 33. South of the old KBO (Urban - Debris/Glass Only)
    {
        x = -35.271, y = -0.497, z = 191.535,
        max_hearing_dist = 118.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 34. South-west of the old KBO (Urban - Debris/Glass Only)
    {
        x = -36.179, y = 0.922, z = 217.217,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 35. West of the old KBO (Urban - Debris/Glass Only)
    {
        x = -40.149, y = -0.284, z = 255.109,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 36. North of the river port (Urban - Debris/Glass Only)
    {
        x = 256.260, y = 0.168, z = 311.930,
        max_hearing_dist = 90.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 37. North of the river port (Urban - Debris/Glass Only)
    {
        x = 262.860, y = 0.167, z = 306.629,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 38. North of the river port (Urban - Debris/Glass Only)
    {
        x = 295.070, y = 0.930, z = 242.722,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 39. North-west of the river port (Urban - Debris/Glass Only)
    {
        x = 284.426, y = 0.673, z = 238.713,
        max_hearing_dist = 90.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 40. West of the river port (Metal Weak Only)
    {
        x = 273.713, y = 8.879, z = 225.761,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 41. North of the river port (Metal Weak Only)
    {
        x = 274.634, y = 6.905, z = 310.040,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 42. North of the river port (Frogs)
    {
        x = 301.399, y = -10.251, z = 327.616,
        max_hearing_dist = 70.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- 43. North of the river port (Frogs)
    {
        x = 308.339, y = -9.929, z = 318.443,
        max_hearing_dist = 70.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- 44. North of the river port (Frogs)
    {
        x = 320.549, y = -9.811, z = 299.863,
        max_hearing_dist = 70.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- 45. North-east of the river port (Frogs)
    {
        x = 337.307, y = -9.638, z = 259.356,
        max_hearing_dist = 70.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },

    -- 46. South of the river port (Full Urban)
    {
        x = 279.011, y = -0.284, z = 126.870,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 47. North-east of the hospital (Full Urban)
    {
        x = 266.051, y = 3.511, z = 105.846,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 48. North of the hospital (Full Urban)
    {
        x = 243.572, y = 3.972, z = 71.647,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 49. North of the hospital (Full Urban)
    {
        x = 222.366, y = 0.011, z = 42.473,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 50. South of the hospital (Full Urban)
    {
        x = 232.818, y = 0.547, z = 11.124,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 51. South of the hospital (Full Urban)
    {
        x = 221.900, y = 0.593, z = -5.783,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 52. South of the hospital (Full Urban)
    {
        x = 204.146, y = 0.538, z = -23.272,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 53. South of the hospital (Full Urban - Elevated)
    {
        x = 204.300, y = 4.444, z = -25.112,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 54. South of the hospital (Full Urban - Elevated)
    {
        x = 219.483, y = 4.447, z = -9.625,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 55. South of the hospital (Full Urban - Elevated)
    {
        x = 227.044, y = 4.449, z = 17.573,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 56. North-west of the hospital (Full Urban)
    {
        x = 195.660, y = 4.445, z = 52.316,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 57. West of the hospital (Full Urban)
    {
        x = 179.068, y = 4.446, z = 31.363,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 58. West of the hospital (Full Urban - High)
    {
        x = 173.104, y = 6.397, z = 17.699,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 59. West of the hospital (Full Urban)
    {
        x = 156.780, y = 4.449, z = 17.188,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 60. West of the hospital (Full Urban)
    {
        x = 157.768, y = 0.689, z = 20.078,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 61. South-west of the hospital (Metal + Debris/Glass)
    {
        x = 151.472, y = -0.293, z = -29.049,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 62. South-west of the hospital (Metal + Debris/Glass)
    {
        x = 158.836, y = 0.310, z = -62.783,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 63. South-west of the hospital (Metal + Debris/Glass)
    {
        x = 142.104, y = -0.508, z = -45.999,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 64. North-east of the dormitory (Metal + Debris/Glass)
    {
        x = 122.757, y = 0.654, z = -48.161,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 65. North-west of the laundromat (Metal + Debris/Glass)
    {
        x = 126.636, y = -0.397, z = -152.663,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 66. South-west of the laundromat (Metal + Debris/Glass)
    {
        x = 138.453, y = -0.099, z = -196.341,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 67. South-west of the laundromat (Urban - Glass/Steps/Debris)
    {
        x = 135.505, y = 4.906, z = -201.818,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 68. North-west of the laundromat (Urban - Glass/Steps/Debris)
    {
        x = 144.775, y = 4.906, z = -174.088,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 69. By the laundromat (Urban - Glass/Steps/Debris)
    {
        x = 156.882, y = -0.096, z = -193.407,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 70. South of the laundromat (Full Urban)
    {
        x = 145.051, y = -0.300, z = -279.713,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 71. South-west of the laundromat (Full Urban)
    {
        x = 71.314, y = 0.912, z = -251.998,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 72. South of the dormitory (Full Urban)
    {
        x = 38.730, y = 0.240, z = -261.986,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 73. South of the dormitory (Full Urban)
    {
        x = 25.799, y = 0.243, z = -252.128,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 74. East of the department store (Full Urban - Elevated)
    {
        x = 4.776, y = 10.656, z = -244.297,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 75. South-west of the laundromat (Full Urban)
    {
        x = 71.707, y = 0.914, z = -233.999,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 76. South-west of the laundromat (Full Urban - Elevated)
    {
        x = 80.598, y = 10.658, z = -244.125,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 77. South-west of the laundromat (Full Urban)
    {
        x = 71.481, y = 0.957, z = -260.216,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 78. East of the dormitory (Full Urban)
    {
        x = 65.009, y = 2.934, z = -136.432,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 79. North-east of the dormitory (Full Urban - Very Elevated)
    {
        x = 61.040, y = 16.525, z = -126.188,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 80. Near the dormitory (Full Urban - Very Elevated)
    {
        x = 49.706, y = 16.556, z = -144.353,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 81. At the dormitory (Full Urban - Very Elevated)
    {
        x = 45.645, y = 16.601, z = -136.661,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 82. North-east of the dormitory (Full Urban)
    {
        x = 91.168, y = 3.396, z = -99.444,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 83. North of the dormitory (Full Urban)
    {
        x = 36.277, y = 2.261, z = -73.019,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 84. North-west of the dormitory (Full Urban)
    {
        x = 17.663, y = 2.210, z = -100.580,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 85. North-west of the dormitory (Full Urban)
    {
        x = 17.673, y = 2.202, z = -100.586,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 86. West of the dormitory (Full Urban)
    {
        x = -6.285, y = 2.224, z = -136.037,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 87. South-east of the playground (Full Urban)
    {
        x = -55.603, y = 2.991, z = -143.375,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 88. East of the playground (Full Urban)
    {
        x = -49.827, y = 0.841, z = -93.795,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 89. East of the playground (Full Urban - Elevated)
    {
        x = -51.722, y = 4.211, z = -103.380,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 90. East of the playground (Full Urban - Elevated)
    {
        x = -72.106, y = 4.211, z = -90.616,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 91. East of the playground (Full Urban - Elevated)
    {
        x = -76.236, y = 4.209, z = -107.962,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 92. North-east of the playground (Full Urban)
    {
        x = -95.630, y = 0.844, z = -94.016,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 93. North of the playground (Full Urban - Elevated)
    {
        x = -108.111, y = 4.205, z = -93.877,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 94. South of the school (Metal)
    {
        x = 69.651, y = -0.213, z = 41.368,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 95. South-west of the school (Metal)
    {
        x = 20.467, y = -0.004, z = 77.097,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 96. East of KBO Jubilee (Urban - Debris/Glass/Steps)
    {
        x = -50.774, y = 0.402, z = 95.034,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 97. West of KBO Jubilee (Urban - Debris/Glass/Steps)
    {
        x = -79.441, y = 0.438, z = 94.807,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 98. By KBO Jubilee (Urban - Debris/Glass/Steps)
    {
        x = -65.472, y = 4.500, z = 93.921,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 99. East of KBO Jubilee (Urban - Debris/Glass/Steps)
    {
        x = -43.920, y = 8.602, z = 94.611,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 100. South-west of KBO Jubilee (Urban - Debris/Glass/Steps)
    {
        x = -73.259, y = 8.602, z = 80.909,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 101. West of KBO Jubilee (Urban - Debris/Glass/Steps)
    {
        x = -81.762, y = 8.600, z = 94.975,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 102. At KBO Jubilee (Urban - Debris/Glass/Steps)
    {
        x = -59.215, y = 8.597, z = 95.069,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 103. North of the school (Urban - Debris/Glass/Steps)
    {
        x = 38.916, y = 1.408, z = 160.122,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 104. South-west of the school (Urban - Debris/Glass/Steps)
    {
        x = 40.824, y = 1.409, z = 118.203,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 105. West of the school (Urban - Debris/Glass/Steps)
    {
        x = 39.946, y = 5.309, z = 128.966,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 106. West of the school (Urban - Debris/Glass/Steps)
    {
        x = 12.226, y = 5.358, z = 126.214,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 107. East of the school (Urban - Debris/Glass/Steps)
    {
        x = 71.479, y = 5.306, z = 123.205,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 108. North of the school (Urban - Debris/Glass/Steps)
    {
        x = 71.328, y = 0.489, z = 169.209,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 109. North of the school (Urban - Debris/Glass/Steps)
    {
        x = 50.476, y = 0.484, z = 168.296,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 110. East of the school (Metal)
    {
        x = 102.826, y = -0.494, z = 153.937,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },

   -- 111. North of the dormitory (Full Urban)
    {
        x = 55.145, y = -0.301, z = -26.532,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 112. North of the dormitory (Full Urban)
    {
        x = 45.111, y = -0.497, z = -26.727,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 113. North of the dormitory (Full Urban)
    {
        x = 11.128, y = -0.426, z = -25.114,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 114. North of the dormitory (Full Urban)
    {
        x = 25.180, y = 2.992, z = -61.009,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 115. South of KBO Jubilee (Full Urban)
    {
        x = -40.401, y = -0.390, z = -4.745,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 116. South of KBO Jubilee (Full Urban)
    {
        x = -51.874, y = -0.427, z = -4.921,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 117. South of KBO Jubilee (Full Urban)
    {
        x = -66.162, y = -0.481, z = -5.094,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 118. East of the Volcano anomaly (Full Urban)
    {
        x = -97.771, y = 2.156, z = -18.485,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 119. North of the playground (Full Urban)
    {
        x = -118.289, y = 2.229, z = -48.718,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 120. North-west of the playground (Full Urban)
    {
        x = -140.962, y = 2.222, z = -82.362,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 121. South of the book store (Full Urban)
    {
        x = -182.068, y = 0.536, z = -359.880,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 122. East of the book store (Full Urban)
    {
        x = -170.925, y = 5.731, z = -350.904,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 123. East of the department store (Full Urban)
    {
        x = -35.454, y = 3.834, z = -277.745,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 124. South of the dormitory (Full Urban)
    {
        x = 21.949, y = 0.242, z = -246.874,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 125. South of the dormitory (Full Urban)
    {
        x = 63.698, y = 0.531, z = -225.131,
        max_hearing_dist = 160.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 126. South of the dormitory (Full Urban)
    {
        x = 21.433, y = 0.324, z = -223.857,
        max_hearing_dist = 180.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
}