-- ARCHIVO: amb_map_l11_pripyat.script

emitters = {
    -- 1. North-east of the Monolith base (Metal)
    {
        x = 101.209, y = -0.623, z = 217.895,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 2. East of the Monolith base (Metal)
    {
        x = 117.992, y = 1.872, z = 204.528,
        max_hearing_dist = 170.0,
        sound_list = {
            {name="hangar_metal_details", chance = 0.9, interval = 10, sound_list_size = 10, last_time = 0, base_volume = 3.5, min_dist = 5.0, max_dist = 10.0},
            {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.5, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
        }
    },
    -- 3. East of the Monolith base (Metal)
    {
        x = 147.853, y = 1.853, z = 199.661,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 4. East of the Monolith base (Urban)
    {
        x = 191.369, y = 5.972, z = 96.595,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 5. East of the Monolith base (Urban)
    {
        x = 187.711, y = 2.786, z = 154.492,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 6. South-east of the Monolith base (Urban)
    {
        x = 165.750, y = -1.047, z = 52.602,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 7. South-east of the Monolith base (Urban)
    {
        x = 127.064, y = -1.072, z = 52.546,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 8. South of the Monolith base (Urban)
    {
        x = 43.902, y = 5.458, z = 34.542,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 9. South of the Monolith base (Urban)
    {
        x = 61.222, y = 2.220, z = 43.385,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 10. South-east of the Monolith base (Urban)
    {
        x = 88.612, y = 2.271, z = 43.179,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 11. South of the Monolith base (Urban)
    {
        x = 24.392, y = -0.937, z = -17.856,
        max_hearing_dist = 90.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 12. South of the Monolith base (Urban)
    {
        x = 59.280, y = -0.917, z = -17.932,
        max_hearing_dist = 90.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 13. North-east of the road to Radar (Metal)
    {
        x = 123.962, y = -2.286, z = -59.044,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 14. South-east of the Monolith base (Urban)
    {
        x = 132.370, y = -0.933, z = -48.859,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 15. South-east of the Monolith base (Urban - Elevated)
    {
        x = 142.962, y = 3.935, z = -10.471,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 16. South-east of the Monolith base (Urban - Elevated)
    {
        x = 112.215, y = 4.020, z = -8.282,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 17. South of the Monolith base (Metal)
    {
        x = 84.351, y = -2.221, z = -19.636,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 18. North of the road to Radar (Urban)
    {
        x = 40.800, y = 0.488, z = -76.367,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 19. North of the road to Radar (Urban)
    {
        x = -11.821, y = 2.568, z = -101.495,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 20. North of the road to Radar (Urban)
    {
        x = 35.496, y = -2.249, z = -192.866,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 21. North of the road to Radar (Urban)
    {
        x = -11.626, y = -2.251, z = -217.329,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 22. North of the road to Radar (Urban)
    {
        x = -19.479, y = 0.491, z = -76.398,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 23. North of the road to Radar (Urban)
    {
        x = -86.153, y = -2.200, z = -68.737,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 24. South of the Monolith base (Metal)
    {
        x = -102.134, y = -2.224, z = -41.514,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 25. South of the Monolith base (Metal)
    {
        x = -91.483, y = 1.724, z = -38.923,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 26. South of the Monolith base (Metal)
    {
        x = -67.247, y = -0.715, z = 18.647,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 27. West of the Monolith base (Urban)
    {
        x = -123.346, y = 0.697, z = 222.328,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 28. West of the Monolith base (Urban)
    {
        x = -109.762, y = 2.786, z = 220.676,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 29. West of the Monolith base (Urban)
    {
        x = -109.668, y = 2.786, z = 203.326,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 30. West of the Monolith base (Urban)
    {
        x = -109.277, y = 2.908, z = 167.880,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 31. North of the Monolith base (Metal)
    {
        x = -45.423, y = -0.579, z = 262.352,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },

-- 32. East of the Monolith base (Urban)
    {
        x = 187.710, y = 3.305, z = 218.301,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 33. East of the Monolith base (Urban)
    {
        x = 187.712, y = 2.786, z = 207.337,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 34. East of the Monolith base (Urban)
    {
        x = 187.582, y = 2.768, z = 155.257,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 35. East of the Monolith base (Urban)
    {
        x = 187.541, y = 2.783, z = 143.043,
        max_hearing_dist = 140.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },

-- 36. North of the Monolith base (Metal)
    {
        x = 32.052, y = 1.568, z = 424.918,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 37. East of the Monolith base (Urban)
    {
        x = 192.379, y = 2.805, z = 200.341,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 38. East of the Monolith base (Urban)
    {
        x = 193.136, y = 2.802, z = 210.009,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
-- Pripyat, east of the Monolith base
    {
        x = 92.655, y = 23.079, z = 206.465,
        max_hearing_dist = 50.0,
        sound_list = {
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 41, sound_list_size = 16, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 38, sound_list_size = 16, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 10.0},
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- Pripyat, east of the Monolith base
    {
        x = 104.062, y = 25.756, z = 206.657,
        max_hearing_dist = 50.0,
        sound_list = {
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 41, sound_list_size = 16, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 38, sound_list_size = 16, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 10.0},
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- Pripyat, east of the Monolith base
    {
        x = 112.029, y = 26.062, z = 206.636,
        max_hearing_dist = 50.0,
        sound_list = {
            {name="big_metal_structure_wind_small", chance = 0.9, interval = 41, sound_list_size = 16, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 10.0},
            {name="big_metal_structure_wind_medium", chance = 0.9, interval = 38, sound_list_size = 16, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 10.0},
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
}