emitters = {
        -- 1. West of the road to Rostok
        {
            x = 11.396, y = -0.551, z = 140.608,
            max_hearing_dist = 60.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 2. West of the parking lot
        {
            x = -80.649, y = -0.000, z = 133.350,
            max_hearing_dist = 80.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 3. West of the parking lot (2)
        {
            x = -99.490, y = 0.046, z = 136.623,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 4. West of the parking lot (Elevated)
        {
            x = -146.662, y = 7.502, z = 157.148,
            max_hearing_dist = 115.0,
            sound_list = {
                {name="hangar_metal_details", chance = 0.9, interval = 10, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            }
        },

	{
            x = -176.378, y = 0.099, z = 132.610,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 6. North-east of the construction site (2)
        {
            x = -165.595, y = 3.179, z = 108.487,
            max_hearing_dist = 60.0,
            sound_list = {
                {name="generic_concrete_large_room", chance = 0.9, interval = 20, sound_list_size = 17, last_time = 0, base_volume = 1.8, min_dist = 5.0, max_dist = 13.0},
                {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 13.0},
            }
        },
        -- 7. South-east of the construction site
        {
            x = -224.529, y = -0.001, z = 44.837,
            max_hearing_dist = 60.0,
            sound_list = {
                {name="generic_concrete_large_room", chance = 0.9, interval = 20, sound_list_size = 17, last_time = 0, base_volume = 1.8, min_dist = 5.0, max_dist = 13.0},
                {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 13.0},
            }
        },
        -- 8. At the construction site
        {
            x = -239.032, y = 0.249, z = 52.424,
            max_hearing_dist = 80.0,
            sound_list = {
                {name="generic_concrete_large_room", chance = 0.9, interval = 20, sound_list_size = 17, last_time = 0, base_volume = 1.8, min_dist = 5.0, max_dist = 13.0},
                {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 13.0},
            }
        },
        -- 9. North of the construction site
        {
            x = -223.050, y = 0.298, z = 110.471,
            max_hearing_dist = 60.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="generic_concrete_large_room", chance = 0.9, interval = 20, sound_list_size = 17, last_time = 0, base_volume = 1.8, min_dist = 5.0, max_dist = 13.0},
                {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 13.0},
            }
        },

 -- 10. North of the construction site
        {
            x = -189.917, y = -0.003, z = 183.564,
            max_hearing_dist = 70.0,
            sound_list = {
                {name="hangar_metal_details", chance = 0.9, interval = 10, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            }
        },
        -- 11. North of the construction site (2)
        {
            x = -255.772, y = 0.297, z = 179.072,
            max_hearing_dist = 80.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 12. North of the construction site (3)
        {
            x = -265.390, y = -0.002, z = 158.410,
            max_hearing_dist = 60.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 13. South-west of the construction site (Elevated)
        {
            x = -247.601, y = 3.943, z = 36.511,
            max_hearing_dist = 70.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 14. South of the construction site
        {
            x = -243.069, y = -0.010, z = -17.984,
            max_hearing_dist = 60.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        }
    }
