-- =================================================================================
-- ARCHIVO: amb_defs.script
-- =================================================================================

-- Generic outdoor sounds
generic_day_outdoor_sounds = {
    {name="crow_idle", chance = 0.9, interval = 45, sound_list_size = 50, last_time = 0, base_volume = 0.2, min_dist = 20.0, max_dist = 55.0},
    {name="crows", chance = 0.9, interval = 40, sound_list_size = 30, last_time = 0, base_volume = 0.4, min_dist = 30.0, max_dist = 50.0},
    {name="wind_weak", chance = 0.9, interval = 35, sound_list_size = 16, last_time = 0, base_volume = 0.4, min_dist = 2.0, max_dist = 12.0},
    {name="uso_default_day", chance = 0.9, interval = 30, sound_list_size = 29, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
    {name="dog", chance = 0.9, interval = 40, sound_list_size = 41, last_time = 0, base_volume = 0.2, min_dist = 35.0, max_dist = 45.0},
    {name="cricket_day", chance = 1.5, interval = 25, sound_list_size = 12, last_time = 0, base_volume = 0.1, min_dist = 15.0, max_dist = 25.0},
    {name="insect_fly", chance = 1.5, interval = 25, sound_list_size = 16, last_time = 0, base_volume = 0.2, min_dist = 6.0, max_dist = 10.0},
}

-- Generic outdoor sounds
generic_night_outdoor_sounds = {
    {name="bats", chance = 0.2, interval = 10, sound_list_size = 6, last_time = 0, base_volume = 1.0, min_dist = 20.0, max_dist = 35.0},
    {name="dogs_howl", chance = 0.9, interval = 65, sound_list_size = 23, last_time = 0, base_volume = 0.9, min_dist = 12.0, max_dist = 30.0},
    {name="crow_night", chance = 0.9, interval = 55, sound_list_size = 15, last_time = 0, base_volume = 0.3, min_dist = 18.0, max_dist = 25.0},
    {name="wind_weak", chance = 0.9, interval = 35, sound_list_size = 16, last_time = 0, base_volume = 0.4, min_dist = 2.0, max_dist = 12.0},
    {name="uso_default_night", chance = 0.9, interval = 60, sound_list_size = 9, last_time = 0, base_volume = 0.2, min_dist = 11.0, max_dist = 25.0},
    {name="insect_night", chance = 0.9, interval = 5, sound_list_size = 20, last_time = 0, base_volume = 0.1, min_dist = 12.0, max_dist = 18.0},
    {name="cricket_night", chance = 0.9, interval = 6, sound_list_size = 18, last_time = 0, base_volume = 0.1, min_dist = 15.0, max_dist = 25.0},
}

-- INDOOR sounds
event_list_cover_indoor = {
    {name="wind_interior", chance = 0.9, interval = 65, sound_list_size = 33, last_time = 0, base_volume = 1.0, min_dist = 1.0, max_dist = 5.0},
}

-- GENERIC UNDERGROUND sounds
event_list_underground = {
    {name="underground_rumble", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 9.0, min_dist = 1.0, max_dist = 1.5},
    {name="underground_metal_debris", chance = 0.9, interval = 10, sound_list_size = 8, last_time = 0, base_volume = 4.30, min_dist = 8.0, max_dist = 12.0},
    {name="underground_metal_rattle", chance = 0.9, interval = 15, sound_list_size = 6, last_time = 0, base_volume = 3.30, min_dist = 3.0, max_dist = 12.0},
    {name="underground_concrete_details", chance = 0.9, interval = 18, sound_list_size = 22, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 12.0},
    {name="underground_water_drops", chance = 0.9, interval = 5, sound_list_size = 26, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 7.0},
    {name="underground_metal_loud", chance = 0.9, interval = 9, sound_list_size = 11, last_time = 0, base_volume = 8.25, min_dist = 10.0, max_dist = 15.0},
    {name="underground_metal_medium", chance = 0.9, interval = 10, sound_list_size = 9, last_time = 0, base_volume = 5.25, min_dist = 8.0, max_dist = 102.0},
    {name="underground_uso", chance = 0.9, interval = 15, sound_list_size = 13, last_time = 0, base_volume = 5.0, min_dist = 5.0, max_dist = 10.0},
    {name="underground_wind_gust", chance = 0.9, interval = 15, sound_list_size = 8, last_time = 0, base_volume = 2.1, min_dist = 5.0, max_dist = 8.0},
    {name="underground_rocks", chance = 0.9, interval = 8, sound_list_size = 29, last_time = 0, base_volume = 3.0, min_dist = 4.0, max_dist = 5.0},
}

-- RAIN GENERIC OUTDOOR
event_list_on_rain_outdoor = {
    {name="wind_weak", chance = 0.9, interval = 45, sound_list_size = 16, last_time = 0, base_volume = 0.4, min_dist = 2.0, max_dist = 12.0},
    {name="uso_default_day", chance = 0.9, interval = 30, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
    {name="small_tree_trunk_weak", chance = 0.9, interval = 20, sound_list_size = 24, last_time = 0, base_volume = 5.0, min_dist = 2.0, max_dist = 5.0},
    {name="small_tree_trunk_strong", chance = 0.9, interval = 30, sound_list_size = 48, last_time = 0, base_volume = 4.0, min_dist = 5.0, max_dist = 10.0},
    {name="leaves", chance = 0.9, interval = 15, sound_list_size = 8, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 10.0}
}

-- RAIN GENERIC INDOOR
event_list_on_rain_indoor = {
    {name="wind_interior", chance = 0.9, interval = 15, sound_list_size = 33, last_time = 0, base_volume = 2.0, min_dist = 1.0, max_dist = 4.0},
}

-- STORM GENERIC OUTDOOR
event_list_on_storm_outdoor = {
    {name="Bush_raindrops", chance = 1.0, interval = 1, sound_list_size = 24, last_time = 0, base_volume = 0.9, min_dist = 1.0, max_dist = 5.0},
    {name="wind_strong", chance = 0.9, interval = 45, sound_list_size = 13, last_time = 0, base_volume = 4.0, min_dist = 3.0, max_dist = 5.0},
    {name="uso_default_day", chance = 0.9, interval = 30, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 6.0, max_dist = 12.0},
    {name="large_tree_trunk_weak", chance = 0.9, interval = 10, sound_list_size = 24, last_time = 0, base_volume = 3.8, min_dist = 10.0, max_dist = 25.0},
    {name="large_tree_trunk_strong", chance = 0.9, interval = 15, sound_list_size = 32, last_time = 0, base_volume = 3.8, min_dist = 15.0, max_dist = 35.0},
    {name="leaves", chance = 0.9, interval = 15, sound_list_size = 8, last_time = 0, base_volume = 3.0, min_dist = 10.0, max_dist = 15.0},
}

-- STORM INDOOR
event_list_on_storm_indoor = {
    {name="wind_interior", chance = 0.9, interval = 45, sound_list_size = 33, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 15.0},
}

-- MAP-SPECIFIC OUTDOOR SOUNDS
map_specific_outdoor_sounds = {

    ["l01_escape"] = { -- Cordon
        day = {
            {name="grass_rustle", chance = 0.9, interval = 12, sound_list_size = 35, last_time = 1, base_volume = 0.1, min_dist = 7.0, max_dist = 10.0},
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="insect_day", chance = 0.9, interval = 10, sound_list_size = 20, last_time = 0, base_volume = 0.2, min_dist = 5.0, max_dist = 15.0},
            {name="birds_day", chance = 2.5, interval = 55, sound_list_size = 7, last_time = 0, base_volume = 0.1, min_dist = 40.0, max_dist = 55.0},
            {name="hawk", chance = 1.0, interval = 60, sound_list_size = 9, last_time = 1, base_volume = 0.3, min_dist = 35.0, max_dist = 50.0},
        },
        night = {
    		{name="cricket_night", chance = 0.9, interval = 6, sound_list_size = 18, last_time = 0, base_volume = 0.1, min_dist = 10.0, max_dist = 25.0},
                {name="birds_night", chance = 0.9, interval = 45, sound_list_size = 20, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 25.0},
        }
    },

    ["l02_garbage"] = { -- Garbage
        day = {
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="insect_day", chance = 0.9, interval = 10, sound_list_size = 20, last_time = 0, base_volume = 0.2, min_dist = 5.0, max_dist = 15.0},

        },
        night = {
            {name="birds_night", chance = 2.5, interval = 55, sound_list_size = 20, last_time = 0, base_volume = 0.5, min_dist = 40.0, max_dist = 55.0},
            {name="fireflies", chance = 0.9, interval = 10, sound_list_size = 2, last_time = 0, base_volume = 1.2, min_dist = 1.0, max_dist = 5.0},
        }
    },

    ["k02_trucks_cemetery"] = { -- Truck Cemetery
        day = {
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="insect_day", chance = 0.9, interval = 10, sound_list_size = 20, last_time = 0, base_volume = 0.2, min_dist = 5.0, max_dist = 15.0},
            {name="birds_day", chance = 2.5, interval = 35, sound_list_size = 7, last_time = 0, base_volume = 0.3, min_dist = 35.0, max_dist = 50.0},
            {name="hawk", chance = 2.5, interval = 65, sound_list_size = 9, last_time = 0, base_volume = 0.3, min_dist = 35.0, max_dist = 50.0},
        },
        night = {
            {name="fireflies", chance = 0.9, interval = 10, sound_list_size = 2, last_time = 0, base_volume = 1.5, min_dist = 1.0, max_dist = 5.0},
            {name="birds_night", chance = 2.5, interval = 55, sound_list_size = 20, last_time = 0, base_volume = 0.5, min_dist = 40.0, max_dist = 55.0},
        }
    },

    ["l03_agroprom"] = { -- Agroprom
        day = {
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="insect_day", chance = 0.9, interval = 10, sound_list_size = 20, last_time = 0, base_volume = 0.2, min_dist = 5.0, max_dist = 15.0},
            {name="hawk", chance = 2.5, interval = 65, sound_list_size = 9, last_time = 0, base_volume = 0.3, min_dist = 35.0, max_dist = 50.0},
        },
        night = {
            {name="dogs_howl", chance = 0.9, interval = 45, sound_list_size = 23, last_time = 0, base_volume = 1.2, min_dist = 10.0, max_dist = 30.0},
        }
    },

    ["l07_military"] = { -- Military Warehouses
        day = {
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="insect_day", chance = 0.9, interval = 10, sound_list_size = 20, last_time = 0, base_volume = 0.2, min_dist = 5.0, max_dist = 15.0},
            {name="birds_day", chance = 2.5, interval = 35, sound_list_size = 7, last_time = 0, base_volume = 0.3, min_dist = 35.0, max_dist = 50.0},
            {name="hawk", chance = 2.5, interval = 65, sound_list_size = 9, last_time = 0, base_volume = 0.3, min_dist = 35.0, max_dist = 50.0},
        },
        night = {
            {name="fireflies", chance = 0.9, interval = 10, sound_list_size = 2, last_time = 0, base_volume = 1.2, min_dist = 1.0, max_dist = 5.0},
        }
    },

    ["l05_bar"] = { -- The Bar / Rostok exterior
        day = {
            {name="flying_garbage", chance = 0.9, interval = 10, sound_list_size = 4, last_time = 0, base_volume = 0.1, min_dist = 5.0, max_dist = 9.0},
            {name="debris_dust", chance = 0.9, interval = 10, sound_list_size = 14, last_time = 0, base_volume = 0.2, min_dist = 3.0, max_dist = 9.0},
        },
        night = {
            {name="dogs_howl", chance = 0.9, interval = 45, sound_list_size = 23, last_time = 0, base_volume = 1.2, min_dist = 10.0, max_dist = 30.0},
        }
    },

    ["l06_rostok"] = { -- Rostok
        day = {
            {name="flying_garbage", chance = 0.9, interval = 10, sound_list_size = 4, last_time = 0, base_volume = 0.1, min_dist = 5.0, max_dist = 9.0},
            {name="debris_dust", chance = 0.9, interval = 10, sound_list_size = 14, last_time = 0, base_volume = 0.2, min_dist = 3.0, max_dist = 9.0},
            {name="uso_urban_day", chance = 0.9, interval = 30, sound_list_size = 22, last_time = 0, base_volume = 0.3, min_dist = 15.0, max_dist = 19.0},

        },
        night = {
            {name="uso_urban_night", chance = 0.9, interval = 30, sound_list_size = 21, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},

        }
    },

    ["k00_marsh"] = { -- Swamps
        day = {
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="uso_swamp_day", chance = 0.9, interval = 30, sound_list_size = 19, last_time = 0, base_volume = 0.1, min_dist = 20.0, max_dist = 28.0},
            {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 1.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 1.5, min_dist = 20.0, max_dist = 30.0},
            {name="insect_swamp_day", chance = 1.5, interval = 18, sound_list_size = 6, last_time = 0, base_volume = 1.8, min_dist = 5.0, max_dist = 12.0},
            {name="insect_swamp_fly", chance = 1.5, interval = 25, sound_list_size = 33, last_time = 0, base_volume = 0.4, min_dist = 6.0, max_dist = 10.0}
        },
        night = {
            {name="uso_swamp_night", chance = 0.9, interval = 30, sound_list_size = 15, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
            {name="insect_swamp_night", chance = 1.5, interval = 18, sound_list_size = 17, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
            {name="frogs_swamp_night", chance = 0.9, interval = 45, sound_list_size = 24, last_time = 0, base_volume = 0.5, min_dist = 36.0, max_dist = 50.0},
            {name="fireflies", chance = 0.9, interval = 10, sound_list_size = 2, last_time = 0, base_volume = 1.2, min_dist = 1.0, max_dist = 5.0}
        }
    },

    ["l08_yantar"] = { -- Yantar
        day = {
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="uso_swamp_day", chance = 0.9, interval = 30, sound_list_size = 19, last_time = 0, base_volume = 0.3, min_dist = 20.0, max_dist = 28.0},
            {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
            {name="insect_swamp_day", chance = 1.5, interval = 18, sound_list_size = 6, last_time = 0, base_volume = 1.8, min_dist = 5.0, max_dist = 12.0},
            {name="insect_swamp_fly", chance = 1.5, interval = 25, sound_list_size = 33, last_time = 0, base_volume = 0.4, min_dist = 6.0, max_dist = 10.0}
        },
        night = {
            {name="uso_swamp_night", chance = 0.9, interval = 30, sound_list_size = 15, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
            {name="insect_swamp_night", chance = 1.5, interval = 18, sound_list_size = 17, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
            {name="frogs_swamp_night", chance = 0.9, interval = 45, sound_list_size = 24, last_time = 0, base_volume = 0.5, min_dist = 36.0, max_dist = 50.0},
            {name="fireflies", chance = 0.9, interval = 10, sound_list_size = 2, last_time = 0, base_volume = 1.2, min_dist = 1.0, max_dist = 5.0},
        }
    },

    ["l10_radar"] = { -- Radar
        day = {
            {name="brain_scorcher_hum", chance = 0.8, interval = 10, sound_list_size = 3, last_time = 0, base_volume = 1.5, min_dist = 15.0, max_dist = 35.0},
        },
        night = {
            {name="brain_scorcher_hum", chance = 0.8, interval = 10, sound_list_size = 3, last_time = 0, base_volume = 1.5, min_dist = 15.0, max_dist = 35.0},
        }
    },

    ["zaton"] = { -- Yantar
        day = {
            {name="uso_swamp_day", chance = 0.9, interval = 30, sound_list_size = 19, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
            {name="frogs_swamp", chance = 0.9, interval = 45, sound_list_size = 32, last_time = 0, base_volume = 0.5, min_dist = 36.0, max_dist = 50.0},
            {name="frogs_swamp_B", chance = 0.9, interval = 45, sound_list_size = 31, last_time = 0, base_volume = 0.5, min_dist = 36.0, max_dist = 50.0},
            {name="insect_swamp_day", chance = 1.5, interval = 18, sound_list_size = 6, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
            {name="insect_swamp_fly", chance = 1.5, interval = 25, sound_list_size = 33, last_time = 0, base_volume = 0.4, min_dist = 6.0, max_dist = 10.0}
        },
        night = {
            {name="uso_swamp_night", chance = 0.9, interval = 30, sound_list_size = 15, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
            {name="insect_swamp_night", chance = 1.5, interval = 18, sound_list_size = 17, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
            {name="frogs_swamp_night", chance = 0.9, interval = 45, sound_list_size = 24, last_time = 0, base_volume = 0.5, min_dist = 36.0, max_dist = 50.0},
            {name="fireflies", chance = 0.9, interval = 10, sound_list_size = 2, last_time = 0, base_volume = 1.2, min_dist = 1.0, max_dist = 5.0}
        }
    },

    ["jupiter"] = { -- Dark Valley
        day = {
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="insect_day", chance = 0.9, interval = 10, sound_list_size = 20, last_time = 0, base_volume = 0.2, min_dist = 5.0, max_dist = 15.0},
            {name="birds_day", chance = 2.5, interval = 35, sound_list_size = 7, last_time = 0, base_volume = 0.2, min_dist = 35.0, max_dist = 50.0},
            {name="hawk", chance = 2.5, interval = 65, sound_list_size = 9, last_time = 0, base_volume = 0.3, min_dist = 35.0, max_dist = 50.0},
        },
        night = {
            {name="fireflies", chance = 0.9, interval = 10, sound_list_size = 2, last_time = 0, base_volume = 1.2, min_dist = 1.0, max_dist = 5.0},
        }
    },

    ["k01_darkscape"] = { -- Dark Valley
        day = {
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="insect_day", chance = 0.9, interval = 10, sound_list_size = 20, last_time = 0, base_volume = 0.2, min_dist = 5.0, max_dist = 15.0},
            {name="birds_day", chance = 2.5, interval = 35, sound_list_size = 7, last_time = 0, base_volume = 0.2, min_dist = 35.0, max_dist = 50.0},
            {name="hawk", chance = 2.5, interval = 65, sound_list_size = 9, last_time = 0, base_volume = 0.3, min_dist = 35.0, max_dist = 50.0},
        },
        night = {
            {name="fireflies", chance = 0.9, interval = 10, sound_list_size = 2, last_time = 0, base_volume = 1.2, min_dist = 1.0, max_dist = 5.0},
        }
    },

    ["l10_limansk"] = { -- Pripyat Town
        day = {
            {name="flying_garbage", chance = 0.9, interval = 10, sound_list_size = 4, last_time = 0, base_volume = 0.1, min_dist = 5.0, max_dist = 9.0},
            {name="debris_dust", chance = 0.9, interval = 10, sound_list_size = 14, last_time = 0, base_volume = 0.2, min_dist = 3.0, max_dist = 9.0},
            {name="uso_urban_day", chance = 0.9, interval = 30, sound_list_size = 22, last_time = 0, base_volume = 0.3, min_dist = 15.0, max_dist = 19.0},
        },
        night = {
            {name="uso_urban_night", chance = 0.9, interval = 30, sound_list_size = 21, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        }
    },

    ["l11_pripyat"] = { -- Pripyat Town
        day = {
            {name="flying_garbage", chance = 0.9, interval = 10, sound_list_size = 4, last_time = 0, base_volume = 0.1, min_dist = 5.0, max_dist = 9.0},
            {name="debris_dust", chance = 0.9, interval = 10, sound_list_size = 14, last_time = 0, base_volume = 0.2, min_dist = 3.0, max_dist = 9.0},
            {name="uso_urban_day", chance = 0.9, interval = 30, sound_list_size = 22, last_time = 0, base_volume = 0.3, min_dist = 15.0, max_dist = 19.0},
        },
        night = {
            {name="uso_urban_night", chance = 0.9, interval = 30, sound_list_size = 21, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        }
    },

    ["pripyat"] = { -- Pripyat Town
        day = {
            {name="flying_garbage", chance = 0.9, interval = 10, sound_list_size = 4, last_time = 0, base_volume = 0.1, min_dist = 5.0, max_dist = 9.0},
            {name="debris_dust", chance = 0.9, interval = 10, sound_list_size = 14, last_time = 0, base_volume = 0.2, min_dist = 3.0, max_dist = 9.0},
            {name="uso_urban_day", chance = 0.9, interval = 30, sound_list_size = 22, last_time = 0, base_volume = 0.3, min_dist = 15.0, max_dist = 19.0},
        },
        night = {
            {name="uso_urban_night", chance = 0.9, interval = 30, sound_list_size = 21, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        }
    },

    ["l12_stancia"] = { -- Pripyat Town
        day = {
            {name="flying_garbage", chance = 0.9, interval = 10, sound_list_size = 4, last_time = 0, base_volume = 0.1, min_dist = 5.0, max_dist = 9.0},
            {name="debris_dust", chance = 0.9, interval = 10, sound_list_size = 14, last_time = 0, base_volume = 0.2, min_dist = 3.0, max_dist = 9.0},
            {name="uso_urban_day", chance = 0.9, interval = 30, sound_list_size = 22, last_time = 0, base_volume = 0.3, min_dist = 15.0, max_dist = 19.0},
        },
        night = {
            {name="uso_urban_night", chance = 0.9, interval = 30, sound_list_size = 21, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        }
    },

    ["l12_stancia_2"] = { -- Pripyat Town
        day = {
            {name="flying_garbage", chance = 0.9, interval = 10, sound_list_size = 4, last_time = 0, base_volume = 0.1, min_dist = 5.0, max_dist = 9.0},
            {name="debris_dust", chance = 0.9, interval = 10, sound_list_size = 14, last_time = 0, base_volume = 0.2, min_dist = 3.0, max_dist = 9.0},
            {name="uso_urban_day", chance = 0.9, interval = 30, sound_list_size = 22, last_time = 0, base_volume = 0.3, min_dist = 15.0, max_dist = 19.0},
        },
        night = {
            {name="uso_urban_night", chance = 0.9, interval = 30, sound_list_size = 21, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        }
    },

    ["l13_generators"] = { -- Pripyat Town
        day = {
            {name="insect_day_idle", chance = 0.9, interval = 15, sound_list_size = 20, last_time = 0, base_volume = 0.3, min_dist = 7.0, max_dist = 18.0},
            {name="insect_day", chance = 0.9, interval = 10, sound_list_size = 20, last_time = 0, base_volume = 0.2, min_dist = 5.0, max_dist = 15.0},
            {name="uso_urban_day", chance = 0.9, interval = 30, sound_list_size = 22, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        },
        night = {
            {name="uso_urban_night", chance = 0.9, interval = 30, sound_list_size = 21, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        }
    },

    ["l12u_control_monolith"] = { -- Pripyat Town
        day = {
            {name="uso_urban_day", chance = 0.9, interval = 30, sound_list_size = 22, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        },
        night = {
            {name="uso_urban_night", chance = 0.9, interval = 30, sound_list_size = 21, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        }
    },

    ["l13u_warlab"] = { -- Pripyat Town
        day = {
            {name="uso_urban_day", chance = 0.9, interval = 30, sound_list_size = 22, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        },
        night = {
            {name="uso_urban_night", chance = 0.9, interval = 30, sound_list_size = 21, last_time = 0, base_volume = 0.9, min_dist = 15.0, max_dist = 19.0},
        }
    },
}

-- MAP-SPECIFIC UNDERGROUND SOUNDS
map_specific_underground_sounds = {

    ["l04u_labx18"] = { -- Lab X18
        {name="lab_x18_scream", chance = 0.05, interval = 300, sound_list_size = 3, last_time = 0, base_volume = 3.0, min_dist = 20.0, max_dist = 60.0},
        {name="lab_x18_demon_breath", chance = 0.1, interval = 180, sound_list_size = 5, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 15.0}
    },

    ["l08u_brainlab"] = { -- Lab X16
        {name="brainlab_hum_strong", chance = 0.9, interval = 20, sound_list_size = 10, last_time = 0, base_volume = 1.5, min_dist = 15.0, max_dist = 30.0},
        {name="psychic_whispers", chance = 0.2, interval = 90, sound_list_size = 7, last_time = 0, base_volume = 1.0, min_dist = 1.0, max_dist = 10.0}
    },

    ["labx8"] = { -- Lab X8
        {name="x8_water_pipes", chance = 0.7, interval = 15, sound_list_size = 12, last_time = 0, base_volume = 0.9, min_dist = 3.0, max_dist = 15.0},
        {name="x8_echo_steps", chance = 0.15, interval = 60, sound_list_size = 4, last_time = 0, base_volume = 0.6, min_dist = 25.0, max_dist = 40.0}
    },

    ["l12u_sarcofag"] = { -- Sarcofag
        {name="sarcofag_monolith_hum", chance = 0.8, interval = 10, sound_list_size = 5, last_time = 0, base_volume = 2.0, min_dist = 10.0, max_dist = 30.0},
        {name="monolith_chant", chance = 0.05, interval = 300, sound_list_size = 1, last_time = 0, base_volume = 1.5, min_dist = 50.0, max_dist = 80.0}
    },

    ["jupiter_underground"] = {},
    ["l03u_agr_underground"] = {},
    ["l10u_bunker"] = {},
    ["l12u_control_monolith"] = {},
    ["l13u_warlab"] = {},
}

-- List of levels considered underground
underground_levels = {
    "jupiter_underground",
    "l03u_agr_underground",
    "l08u_brainlab",
    "labx8",
    "l12u_sarcofag",
    "l10u_bunker",
    "l04u_labx18",
    "l12u_control_monolith",
    "l13u_warlab",
}

-- =================================================================================
-- CONFIGURACIÓN DE LOOPS DE LLUVIA (RAIN LOOPS)
-- Aquí definimos los nombres de los archivos .ogg para cada intensidad
-- =================================================================================
rain_loop_settings = {
    -- Lluvia suave (rain_factor > 0.05)
    weak   = { file = "rain_loop_weak",   volume = 4.0 }, 

    -- Lluvia media (rain_factor > 0.7)
    medium = { file = "rain_loop_medium", volume = 5.0 }, 

    -- Tormenta fuerte (rain_factor > 0.9)
    storm  = { file = "rain_loop_storm",  volume = 1.0 }  
}