emitters = {
        -- 1. South of bandit base
        {
            x = 4.590, y = 1.236, z = -32.292,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 2. East of bandit base
        {
            x = 47.063, y = -0.056, z = 10.836,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 3. North of bandit base
        {
            x = 28.820, y = 0.035, z = 34.784,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 4. North-west of bandit base
        {
            x = -2.608, y = 0.091, z = 35.996,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 5. South of bandit base (2)
        {
            x = 27.908, y = 0.455, z = -36.514,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 6. North of factory
        {
            x = -3.432, y = 0.117, z = -69.478,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 7. East of factory
        {
            x = 34.298, y = 0.064, z = -94.602,
            max_hearing_dist = 150.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 12.0},
                {name="hangar_metal_details", chance = 0.9, interval = 10, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
            }
        },
        -- 8. West of gas station
        {
            x = 96.245, y = 0.096, z = -70.244,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 9. Construction site / Fireball area 1
        {
            x = 121.378, y = 8.814, z = -262.294,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.9, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.9, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 10. Construction site / Fireball area 2
        {
            x = 142.055, y = 0.171, z = -281.852,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_metal_details", chance = 0.9, interval = 10, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
                {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},

            }
        },
        -- 11. Construction site / Fireball area 3
        {
            x = 125.039, y = -1.370, z = -229.994,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_metal_details", chance = 0.9, interval = 10, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
                {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
            }
        },
        -- 12. Construction site / Fireball area 4
        {
            x = 144.399, y = 0.223, z = -260.287,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="hangar_details", chance = 0.9, interval = 10, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_metal_details", chance = 0.9, interval = 10, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 12, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 10.0},
                {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
                {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
            }
        },
        -- 13. Construction site / Fireball area 5
        {
            x = 151.090, y = 10.313, z = -247.726,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="hangar_details", chance = 0.9, interval = 25, sound_list_size = 12, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 13.0},
                {name="hangar_metal_details", chance = 0.9, interval = 50, sound_list_size = 10, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 12.0},
                {name="hangar_wind_gust", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 3.0, min_dist = 5.0, max_dist = 12.0},
                {name="big_metal_structure_wind_small", chance = 0.9, interval = 20, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
                {name="big_metal_structure_wind_medium", chance = 0.9, interval = 30, sound_list_size = 16, last_time = 0, base_volume = 2.5, min_dist = 5.0, max_dist = 10.0},
            }
        },
        -- 14. Swamp West of fireball 1 (FROGS)
        {
            x = 42.461, y = -5.431, z = -339.493,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="frogs_swamp", chance = 0.9, interval = 6, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
                {name="frogs_swamp_B", chance = 0.8, interval = 8, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
            }
        },
        -- 15. Swamp West of fireball 2 (FROGS)
        {
            x = 11.710, y = -5.576, z = -329.653,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="frogs_swamp", chance = 0.9, interval = 6, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
                {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
            }
        },
        -- 16. Swamp West of fireball 3 (FROGS)
        {
            x = -16.259, y = -4.029, z = -279.290,
            max_hearing_dist = 100.0,
            sound_list = {
                {name="frogs_swamp", chance = 0.9, interval = 6, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
                {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
            }
        },
        {
            x = -36.100, y = -4.900, z = -250.044,
            max_hearing_dist = 150.0,
            sound_list = {
                {name="frogs_swamp", chance = 0.9, interval = 5, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
                {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
            }
        },
        -- 17. Abandoned Farm / Base 1 (METAL)
        {
            x = -132.357, y = 0.318, z = -460.430,
            max_hearing_dist = 130.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 10, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
            }
        },
        -- 18. Abandoned Farm / Base 2 (METAL)
        {
            x = -118.636, y = 0.779, z = -502.263,
            max_hearing_dist = 130.0,
            sound_list = {
                {name="metal_structure_small_strong", chance = 0.9, interval = 20, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 9.0, max_dist = 13.0},
                {name="metal_structure_small_weak", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 11.0, max_dist = 13.0},
            }
        },

    }
