-- ARCHIVO: amb_map_l10_limansk.script

emitters = {
    -- 1. South of the road to Dead City (Metal)
    {
        x = -47.338, y = -0.994, z = -255.021,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 2. North of the road to Dead City (Metal)
    {
        x = -65.225, y = -5.064, z = -197.835,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 3. South of the gastronom (Urban)
    {
        x = -57.882, y = -0.929, z = -186.590,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 4. South-east of the gastronom (Urban)
    {
        x = -27.245, y = -0.460, z = -185.344,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 5. North-east of the road to Dead City (Urban)
    {
        x = -14.086, y = -3.868, z = -204.801,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 6. East of the road to Dead City (Urban)
    {
        x = 7.316, y = -2.913, z = -250.194,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 7. South-east of the road to Dead City (Urban)
    {
        x = -5.057, y = 1.425, z = -265.326,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 8. North of the tunnel to Red Forest (Urban)
    {
        x = 18.462, y = 3.657, z = -286.752,
        max_hearing_dist = 90.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 9. South-east of the road to Dead City (Urban)
    {
        x = -13.720, y = 1.337, z = -291.323,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 10. North of the tunnel to Red Forest (Urban)
    {
        x = -18.606, y = 1.855, z = -311.035,
        max_hearing_dist = 115.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 11. North-west of the tunnel to Red Forest (Metal)
    {
        x = -33.734, y = 1.505, z = -326.724,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 12. By the tunnel to Red Forest (Tunnel/Concrete)
    {
        x = 3.661, y = -0.012, z = -360.713,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="generic_concrete_large_room", chance = 0.9, interval = 10, sound_list_size = 17, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 13.0},
            {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
        }
    },
    -- 13. South of the tunnel to Red Forest (Tunnel/Concrete)
    {
        x = 8.127, y = -0.011, z = -378.720,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="generic_concrete_large_room", chance = 0.9, interval = 10, sound_list_size = 17, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 13.0},
            {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
        }
    },
    -- 14. East of the road to Dead City (Metal)
    {
        x = 34.796, y = 1.135, z = -270.970,
        max_hearing_dist = 115.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 15. Near the gastronom (Full Urban)
    {
        x = -48.342, y = -2.153, z = -153.668,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 16. North-east of the gastronom (Full Urban)
    {
        x = -13.029, y = -4.571, z = -116.093,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 17. East of the gastronom (Full Urban)
    {
        x = -16.795, y = -3.123, z = -150.927,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 18. East of the gastronom (Metal)
    {
        x = 10.829, y = -4.975, z = -121.145,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 19. North of the gastronom (Metal)
    {
        x = -34.011, y = -5.053, z = -80.188,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 20. South-west of the bridge outpost (Metal)
    {
        x = -35.819, y = -5.075, z = -46.761,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 21. North of the gastronom (Full Urban)
    {
        x = -13.348, y = -5.000, z = -63.164,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 22. South of the bridge outpost (Full Urban)
    {
        x = -5.827, y = -4.897, z = -38.277,
        max_hearing_dist = 90.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 23. South of the bridge outpost (Full Urban)
    {
        x = 34.104, y = 2.081, z = -52.903,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 24. South of the bridge outpost (Full Urban)
    {
        x = 23.019, y = 2.078, z = -55.721,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 25. South of the bridge outpost (Full Urban)
    {
        x = 34.208, y = 2.080, z = -68.521,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 26. South-west of the bridge outpost (Metal)
    {
        x = -20.247, y = -7.002, z = -16.731,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 27. South-west of the bridge outpost (Frogs)
    {
        x = -16.759, y = -10.812, z = -1.714,
        max_hearing_dist = 90.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
            {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- 28. South-west of the bridge outpost (Frogs)
    {
        x = -0.999, y = -10.758, z = 0.234,
        max_hearing_dist = 100.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
        }
    },
    -- 29. South of the bridge outpost (Frogs)
    {
        x = 24.052, y = -10.659, z = -8.362,
        max_hearing_dist = 70,
        sound_list = {
            {name="frogs_swamp_B", chance = 0.8, interval = 5, sound_list_size = 31, last_time = 0, base_volume = 3.5, min_dist = 10.0, max_dist = 15.0},
        }
    },
    -- 30. South-east of the bridge outpost (Frogs)
    {
        x = 60.454, y = -10.354, z = -19.589,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="frogs_swamp", chance = 0.9, interval = 10, sound_list_size = 32, last_time = 0, base_volume = 3.5, min_dist = 15.0, max_dist = 25.0},
        }
    },
    -- 31. South of the bridge outpost (Metal)
    {
        x = 55.818, y = -7.002, z = -38.256,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },

    -- 32. North-west of the construction site (Metal)
    {
        x = -17.477, y = 16.303, z = 206.180,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 33. North-west of the bridge outpost (Urban)
    {
        x = 17.854, y = 2.126, z = 44.748,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 34. North-east of the bridge outpost (Urban)
    {
        x = 34.657, y = -2.418, z = 50.993,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 35. North of the bridge outpost (Urban)
    {
        x = 4.080, y = 3.968, z = 74.059,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 36. East of the bridge outpost (Metal)
    {
        x = 47.813, y = -6.006, z = 45.657,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 37. South-west of the construction site (Metal)
    {
        x = -21.892, y = -4.002, z = 133.737,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 38. East of the construction site (Metal)
    {
        x = 41.456, y = 14.070, z = 176.970,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 39. North-east of the construction site (Metal)
    {
        x = 30.775, y = 12.973, z = 208.381,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 40. North-east of the construction site (Concrete)
    {
        x = 29.882, y = 17.082, z = 197.002,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="generic_concrete_large_room", chance = 0.9, interval = 10, sound_list_size = 17, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 13.0},
            {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
        }
    },
    -- 41. By the construction site (Concrete)
    {
        x = 13.703, y = 13.679, z = 192.244,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="generic_concrete_large_room", chance = 0.9, interval = 10, sound_list_size = 17, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 13.0},
            {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
        }
    },
    -- 42. North-west of the construction site (Concrete)
    {
        x = -1.057, y = 20.858, z = 192.544,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="generic_concrete_large_room", chance = 0.9, interval = 10, sound_list_size = 17, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 13.0},
            {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
        }
    },
    -- 43. East of the construction site (Concrete)
    {
        x = 30.661, y = 24.745, z = 191.401,
        max_hearing_dist = 80.0,
        sound_list = {
            {name="generic_concrete_large_room", chance = 0.9, interval = 10, sound_list_size = 17, last_time = 0, base_volume = 2.0, min_dist = 5.0, max_dist = 13.0},
            {name="underground_concrete_details", chance = 0.9, interval = 15, sound_list_size = 22, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
        }
    },
    -- 44. North of the construction site (Metal)
    {
        x = 12.811, y = 3.607, z = 245.335,
        max_hearing_dist = 120.0,
        sound_list = {
            {name="metal_structure_small_strong", chance = 0.9, interval = 25, sound_list_size = 20, last_time = 0, base_volume = 1.5, min_dist = 5.0, max_dist = 13.0},
            {name="metal_structure_small_weak", chance = 0.9, interval = 12, sound_list_size = 32, last_time = 0, base_volume = 1.3, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 45. South of the radiowave institute (Full Urban)
    {
        x = 85.870, y = 7.341, z = 241.857,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 46. South of the radiowave institute (Full Urban)
    {
        x = 75.788, y = 7.349, z = 245.996,
        max_hearing_dist = 110.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 47. By the radiowave institute (Full Urban)
    {
        x = 60.186, y = 3.299, z = 298.032,
        max_hearing_dist = 130.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
    -- 48. West of the radiowave institute (Full Urban)
    {
        x = 28.314, y = 3.300, z = 313.785,
        max_hearing_dist = 150.0,
        sound_list = {
            {name="urban_debris", chance = 0.9, interval = 15, sound_list_size = 16, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 13.0},
            {name="urban_glass", chance = 0.9, interval = 40, sound_list_size = 18, last_time = 0, base_volume = 0.9, min_dist = 5.0, max_dist = 12.0},
            {name="urban_steps", chance = 0.9, interval = 10, sound_list_size = 11, last_time = 0, base_volume = 1.0, min_dist = 5.0, max_dist = 12.0},
            {name="urban_windows", chance = 0.9, interval = 15, sound_list_size = 18, last_time = 0, base_volume = 0.8, min_dist = 5.0, max_dist = 12.0},
        }
    },
}