-- =================================================================================
-- ARCHIVO: rain_amb_map_l05_bar.script
-- =================================================================================

emitters = {
    -- 1. North of the Duty base (Metal)
    {
        x = 211.395, y = -0.002, z = 110.421,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 2. South-east of the Duty base (Metal)
    {
        x = 269.354, y = 2.877, z = 0.535,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 3. South-east of the entrance to the bar (Metal)
    {
        x = 225.954, y = 1.755, z = -40.724,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 4. South-east of the entrance to the bar (Metal)
    {
        x = 270.034, y = 6.478, z = -135.440,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 5. South-east of the entrance to the bar (Metal)
    {
        x = 295.893, y = 4.397, z = -132.678,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 6. South-east of the entrance to the bar (Metal)
    {
        x = 307.372, y = 4.323, z = -143.499,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 7. South of the Duty base (Metal)
    {
        x = 333.516, y = 3.442, z = -150.410,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 8. South of the Duty base (Metal)
    {
        x = 347.313, y = 10.860, z = -179.728,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 9. South of the Duty base (Metal)
    {
        x = 362.972, y = 11.808, z = -180.390,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 10. South of the Duty base (Metal)
    {
        x = 384.211, y = 20.781, z = -252.327,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 11. West of the Duty base (Metal)
    {
        x = 162.599, y = 2.113, z = 115.492,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 12. North of the entrance to the bar (Metal)
    {
        x = 118.749, y = 0.609, z = 80.279,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 13. North-west of the western checkpoint (Metal)
    {
        x = 77.818, y = 0.933, z = 149.133,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 14. North of the western checkpoint (Metal)
    {
        x = 58.683, y = 2.403, z = 197.495,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 15. South of the road to the Army Warehouses (Metal)
    {
        x = 21.792, y = 1.081, z = 249.127,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    },

    -- 16. South of the road to the Army Warehouses (Metal)
    {
        x = 38.812, y = 1.584, z = 257.112,
        max_hearing_dist = 40.0,
        sound_list = {
            {name="raindrops_metal", chance = 1.0, interval = 0.2, sound_list_size = 20, last_time = 0, base_volume = 2.5, min_dist = 2.0, max_dist = 2.5},
        }
    }
}